services:
#Database service for Keycloak
  postgres:
    image: postgres:15
    environment:
      POSTGRES_HOST: localhost
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U keycloak"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

#Adminer service for database management
  adminer:
    image: adminer:latest
    restart: unless-stopped
    ports:
      - "8081:8081"
#Keycloak service configuration
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    environment:
      KC_HOSTNAME: localhost
      #KC_HOSTNAME_PORT: 443
      #KC_PROXY: edge
      KC_HEALTH_ENABLED: "true"
      KC_LOG_LEVEL: info
      KC_DB: postgres
      KC_DB_URL_HOST: postgres
      KC_DB_URL_DATABASE: keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password 

      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    #healthcheck:
     # test: /health/ready
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    command: start-dev
    ports:
      - "8080:8080"
    expose:
      - "8080"

#  nginx:
 #   image: nginx:1.25.4
 #   volumes:
  #    - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
   #   - type: bind
    #    source: ./nginx/certs/cert.pem
     #   target: /etc/nginx/certs/cert.pem
      #  read_only: true
      #- type: bind
       # source: ./nginx/certs/key.pem
       # target: /etc/nginx/certs/key.pem
       # read_only: true
    #ports:
    #  - "443:443"
     # - "80:80"
    #depends_on:
     # - keycloak
    #restart: unless-stopped


#Volumes for persistent storage for Postgres
volumes:
  postgres_data: